// Copyright 2025 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package clint_reg_pkg;

    localparam CLINT_REG_DATA_WIDTH = 32;
    localparam CLINT_REG_MIN_ADDR_WIDTH = 16;
    localparam CLINT_REG_SIZE = 'hc000;
    localparam NumCores = 'h2;

    typedef struct {
        logic [31:0] next;
        logic we;
    } clint__mtime__low__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } clint__mtime__high__in_t;

    typedef struct {
        clint__mtime__low__in_t low;
        clint__mtime__high__in_t high;
    } clint__mtime__in_t;

    typedef struct {
        clint__mtime__in_t mtime;
    } clint__in_t;

    typedef struct {
        logic value;
    } clint__msip__pending__out_t;

    typedef struct {
        clint__msip__pending__out_t pending;
    } clint__msip__out_t;

    typedef struct {
        logic [31:0] value;
    } clint__mtimecmp__low__out_t;

    typedef struct {
        logic [31:0] value;
    } clint__mtimecmp__high__out_t;

    typedef struct {
        clint__mtimecmp__low__out_t low;
        clint__mtimecmp__high__out_t high;
    } clint__mtimecmp__out_t;

    typedef struct {
        logic [31:0] value;
    } clint__mtime__low__out_t;

    typedef struct {
        logic [31:0] value;
    } clint__mtime__high__out_t;

    typedef struct {
        clint__mtime__low__out_t low;
        clint__mtime__high__out_t high;
    } clint__mtime__out_t;

    typedef struct {
        clint__msip__out_t msip[2];
        clint__mtimecmp__out_t mtimecmp[2];
        clint__mtime__out_t mtime;
    } clint__out_t;
endpackage
