// Copyright 2025 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module clint_reg (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [15:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input clint_reg_pkg::clint__in_t hwif_in,
        output clint_reg_pkg::clint__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [15:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[15:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic msip[2];
        struct {
            logic low;
            logic high;
        } mtimecmp[2];
        struct {
            logic low;
            logic high;
        } mtime;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.msip[i0] = cpuif_req_masked & (cpuif_addr == 16'h0 + (16)'(i0) * 16'h4);
        end
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.mtimecmp[i0].low = cpuif_req_masked & (cpuif_addr == 16'h4000 + (16)'(i0) * 16'h8);
            decoded_reg_strb.mtimecmp[i0].high = cpuif_req_masked & (cpuif_addr == 16'h4004 + (16)'(i0) * 16'h8);
        end
        decoded_reg_strb.mtime.low = cpuif_req_masked & (cpuif_addr == 16'hbff8);
        decoded_reg_strb.mtime.high = cpuif_req_masked & (cpuif_addr == 16'hbffc);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } pending;
        } msip[2];
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } low;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } high;
        } mtimecmp[2];
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } low;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } high;
        } mtime;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } pending;
        } msip[2];
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } low;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } high;
        } mtimecmp[2];
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } low;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } high;
        } mtime;
    } field_storage_t;
    field_storage_t field_storage;

    for(genvar i0=0; i0<2; i0++) begin
        // Field: clint.msip[].pending
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.msip[i0].pending.value;
            load_next_c = '0;
            if(decoded_reg_strb.msip[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.msip[i0].pending.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.msip[i0].pending.next = next_c;
            field_combo.msip[i0].pending.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.msip[i0].pending.value <= 1'h0;
            end else begin
                if(field_combo.msip[i0].pending.load_next) begin
                    field_storage.msip[i0].pending.value <= field_combo.msip[i0].pending.next;
                end
            end
        end
        assign hwif_out.msip[i0].pending.value = field_storage.msip[i0].pending.value;
    end
    for(genvar i0=0; i0<2; i0++) begin
        // Field: clint.mtimecmp[].low.value
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.mtimecmp[i0].low.value.value;
            load_next_c = '0;
            if(decoded_reg_strb.mtimecmp[i0].low && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.mtimecmp[i0].low.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.mtimecmp[i0].low.value.next = next_c;
            field_combo.mtimecmp[i0].low.value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.mtimecmp[i0].low.value.value <= 32'h0;
            end else begin
                if(field_combo.mtimecmp[i0].low.value.load_next) begin
                    field_storage.mtimecmp[i0].low.value.value <= field_combo.mtimecmp[i0].low.value.next;
                end
            end
        end
        assign hwif_out.mtimecmp[i0].low.value.value = field_storage.mtimecmp[i0].low.value.value;
        // Field: clint.mtimecmp[].high.value
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.mtimecmp[i0].high.value.value;
            load_next_c = '0;
            if(decoded_reg_strb.mtimecmp[i0].high && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.mtimecmp[i0].high.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.mtimecmp[i0].high.value.next = next_c;
            field_combo.mtimecmp[i0].high.value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.mtimecmp[i0].high.value.value <= 32'h0;
            end else begin
                if(field_combo.mtimecmp[i0].high.value.load_next) begin
                    field_storage.mtimecmp[i0].high.value.value <= field_combo.mtimecmp[i0].high.value.next;
                end
            end
        end
        assign hwif_out.mtimecmp[i0].high.value.value = field_storage.mtimecmp[i0].high.value.value;
    end
    // Field: clint.mtime.low.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mtime.low.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.mtime.low && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mtime.low.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end else if(hwif_in.mtime.low.value.we) begin // HW Write - we
            next_c = hwif_in.mtime.low.value.next;
            load_next_c = '1;
        end
        field_combo.mtime.low.value.next = next_c;
        field_combo.mtime.low.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.mtime.low.value.value <= 32'h0;
        end else begin
            if(field_combo.mtime.low.value.load_next) begin
                field_storage.mtime.low.value.value <= field_combo.mtime.low.value.next;
            end
        end
    end
    assign hwif_out.mtime.low.value.value = field_storage.mtime.low.value.value;
    // Field: clint.mtime.high.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mtime.high.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.mtime.high && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mtime.high.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end else if(hwif_in.mtime.high.value.we) begin // HW Write - we
            next_c = hwif_in.mtime.high.value.next;
            load_next_c = '1;
        end
        field_combo.mtime.high.value.next = next_c;
        field_combo.mtime.high.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.mtime.high.value.value <= 32'h0;
        end else begin
            if(field_combo.mtime.high.value.load_next) begin
                field_storage.mtime.high.value.value <= field_combo.mtime.high.value.next;
            end
        end
    end
    assign hwif_out.mtime.high.value.value = field_storage.mtime.high.value.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[8];
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 1 + 0][0:0] = (decoded_reg_strb.msip[i0] && !decoded_req_is_wr) ? field_storage.msip[i0].pending.value : '0;
        assign readback_array[i0 * 1 + 0][31:1] = (decoded_reg_strb.msip[i0] && !decoded_req_is_wr) ? 31'h0 : '0;
    end
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 2 + 2][31:0] = (decoded_reg_strb.mtimecmp[i0].low && !decoded_req_is_wr) ? field_storage.mtimecmp[i0].low.value.value : '0;
        assign readback_array[i0 * 2 + 3][31:0] = (decoded_reg_strb.mtimecmp[i0].high && !decoded_req_is_wr) ? field_storage.mtimecmp[i0].high.value.value : '0;
    end
    assign readback_array[6][31:0] = (decoded_reg_strb.mtime.low && !decoded_req_is_wr) ? field_storage.mtime.low.value.value : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.mtime.high && !decoded_req_is_wr) ? field_storage.mtime.high.value.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<8; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
