# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-generated:
    name: Check generated sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: bender install
        uses: pulp-platform/pulp-actions/bender-install@v2.5.1
        with:
          version: 0.31.0
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Check generated sources
        run: |
          make src/clint_reg.sv CLINT_CORES=2 && test -z "$(git status --porcelain)"
          make src/clint_reg.sv CLINT_CORES=4 && test -n "$(git status --porcelain)"
          make src/clint_reg.sv CLINT_CORES=2 && test -z "$(git status --porcelain)"

  verilator-sim:
    name: Run Verilator simulation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: bender install
        uses: pulp-platform/pulp-actions/bender-install@v2.5.1
        with:
          version: 0.32.1
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Install Verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Run Verilator simulation
        run: make vlt-run

  check-verilog:
    name: Check Verilog sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Run Verible
      uses: chipsalliance/verible-linter-action@main
      with:
        paths: src/clint.sv
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: fsfe/reuse-action@v6.0.0
