# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-generated:
    name: Check generated sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bender install
        uses: pulp-platform/pulp-actions/bender-install@v2.4.3
        with:
          version: 0.28.2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Check generated sources
        run: |
          make src/clint_reg.sv CLINTCORES=2 && test -z "$(git status --porcelain)"
          make src/clint_reg.sv CLINTCORES=4 && test -n "$(git status --porcelain)"
          make src/clint_reg.sv CLINTCORES=2 && test -z "$(git status --porcelain)"

  verilator-sim:
    name: Run Verilator simulation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bender install
        uses: pulp-platform/pulp-actions/bender-install@v2.4.4
        with:
          version: 0.31.0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install Verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Run Verilator simulation
        run: make vlt-run

  check-verilog:
    name: Check Verilog sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Verible
      uses: chipsalliance/verible-linter-action@main
      with:
        paths: src/clint.sv
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check

  check-license:
    name: Check license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pulp-platform/pulp-actions/lint-license@v2.4.3
      with:
        license: |
          Copyright (\d{4}(-\d{4})?\s)?(ETH Zurich and University of Bologna|lowRISC contributors).
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
